baseURL = "https://mikeliang2.github.io/Portfolio/"
languageCode = 'en-us'
title = 'My main page'
theme = 'ananke'

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true

