baseURL = "https://mikeliang2.github.io/Portfolio/"
languageCode = 'en-us'
title = 'My main page'
theme = 'ananke'

[menu]

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 1

  [[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 2

  [[menu.main]]
    name = "Work"
    url = "/working experience/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
      [markup.goldmark.renderHooks.link]
        enableDefault = true
      [markup.goldmark.renderer]
        unsafe = true
[params]
  mainSections = []
  [params.ananke]
    show_recent_posts = false
